/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './conf/__root'
import { Route as DashboardRouteImport } from './conf/_dashboard.route'
import { Route as AuthRouteImport } from './conf/_auth.route'
import { Route as IndexRouteImport } from './conf/index.route'
import { Route as DashboardLeaderboardRouteImport } from './conf/_dashboard/leaderboard.route'
import { Route as DashboardAuthenticatedRouteImport } from './conf/_dashboard/_authenticated.route'
import { Route as AuthRegisterRouteImport } from './conf/_auth/register.route'
import { Route as AuthLogoutRouteImport } from './conf/_auth/logout.route'
import { Route as AuthLoginRouteImport } from './conf/_auth/login.route'
import { Route as DashboardSystemsIndexRouteImport } from './conf/_dashboard/systems/index.route'
import { Route as DashboardAgentsIndexRouteImport } from './conf/_dashboard/agents/index.route'
import { Route as DashboardAgentsAgentSymbolRouteImport } from './conf/_dashboard/agents/$agentSymbol.route'
import { Route as DashboardAuthenticatedSurveysRouteImport } from './conf/_dashboard/_authenticated/surveys.route'
import { Route as DashboardAuthenticatedFleetRouteImport } from './conf/_dashboard/_authenticated/fleet.route'
import { Route as DashboardAuthenticatedContractsRouteImport } from './conf/_dashboard/_authenticated/contracts.route'
import { Route as DashboardSystemsSystemSymbolIndexRouteImport } from './conf/_dashboard/systems/$systemSymbol/index.route'
import { Route as DashboardAuthenticatedFleetIndexRouteImport } from './conf/_dashboard/_authenticated/fleet/index.route'
import { Route as DashboardAuthenticatedFleetShipSymbolRouteImport } from './conf/_dashboard/_authenticated/fleet/$shipSymbol.route'
import { Route as DashboardSystemsSystemSymbolWaypointWaypointSymbolRouteImport } from './conf/_dashboard/systems/$systemSymbol/waypoint/$waypointSymbol.route'
import { Route as DashboardAuthenticatedFleetShipSymbolOverlayRouteImport } from './conf/_dashboard/_authenticated/fleet/$shipSymbol/_overlay.route'
import { Route as DashboardAuthenticatedFleetShipSymbolOverlayMarketRouteImport } from './conf/_dashboard/_authenticated/fleet/$shipSymbol/_overlay.market.route'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./conf/_dashboard.lazy').then((d) => d.Route))

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLeaderboardRouteRoute = DashboardLeaderboardRouteImport.update({
  path: '/leaderboard',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./conf/_dashboard/leaderboard.lazy').then((d) => d.Route),
)

const DashboardAuthenticatedRouteRoute =
  DashboardAuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const AuthRegisterRouteRoute = AuthRegisterRouteImport.update({
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./conf/_auth/register.lazy').then((d) => d.Route))

const AuthLogoutRouteRoute = AuthLogoutRouteImport.update({
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginRouteRoute = AuthLoginRouteImport.update({
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./conf/_auth/login.lazy').then((d) => d.Route))

const DashboardSystemsIndexRouteRoute = DashboardSystemsIndexRouteImport.update(
  {
    path: '/systems/',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
).lazy(() =>
  import('./conf/_dashboard/systems/index.lazy').then((d) => d.Route),
)

const DashboardAgentsIndexRouteRoute = DashboardAgentsIndexRouteImport.update({
  path: '/agents/',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./conf/_dashboard/agents/index.lazy').then((d) => d.Route),
)

const DashboardAgentsAgentSymbolRouteRoute =
  DashboardAgentsAgentSymbolRouteImport.update({
    path: '/agents/$agentSymbol',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./conf/_dashboard/agents/$agentSymbol.lazy').then((d) => d.Route),
  )

const DashboardAuthenticatedSurveysRouteRoute =
  DashboardAuthenticatedSurveysRouteImport.update({
    path: '/surveys',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./conf/_dashboard/_authenticated/surveys.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardAuthenticatedFleetRouteRoute =
  DashboardAuthenticatedFleetRouteImport.update({
    path: '/fleet',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)

const DashboardAuthenticatedContractsRouteRoute =
  DashboardAuthenticatedContractsRouteImport.update({
    path: '/contracts',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./conf/_dashboard/_authenticated/contracts.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardSystemsSystemSymbolIndexRouteRoute =
  DashboardSystemsSystemSymbolIndexRouteImport.update({
    path: '/systems/$systemSymbol/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./conf/_dashboard/systems/$systemSymbol/index.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardAuthenticatedFleetIndexRouteRoute =
  DashboardAuthenticatedFleetIndexRouteImport.update({
    path: '/',
    getParentRoute: () => DashboardAuthenticatedFleetRouteRoute,
  } as any).lazy(() =>
    import('./conf/_dashboard/_authenticated/fleet/index.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardAuthenticatedFleetShipSymbolRouteRoute =
  DashboardAuthenticatedFleetShipSymbolRouteImport.update({
    path: '/$shipSymbol',
    getParentRoute: () => DashboardAuthenticatedFleetRouteRoute,
  } as any).lazy(() =>
    import('./conf/_dashboard/_authenticated/fleet/$shipSymbol.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardSystemsSystemSymbolWaypointWaypointSymbolRouteRoute =
  DashboardSystemsSystemSymbolWaypointWaypointSymbolRouteImport.update({
    path: '/systems/$systemSymbol/waypoint/$waypointSymbol',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import(
      './conf/_dashboard/systems/$systemSymbol/waypoint/$waypointSymbol.lazy'
    ).then((d) => d.Route),
  )

const DashboardAuthenticatedFleetShipSymbolOverlayRouteRoute =
  DashboardAuthenticatedFleetShipSymbolOverlayRouteImport.update({
    id: '/_overlay',
    getParentRoute: () => DashboardAuthenticatedFleetShipSymbolRouteRoute,
  } as any).lazy(() =>
    import(
      './conf/_dashboard/_authenticated/fleet/$shipSymbol/_overlay.lazy'
    ).then((d) => d.Route),
  )

const DashboardAuthenticatedFleetShipSymbolOverlayMarketRouteRoute =
  DashboardAuthenticatedFleetShipSymbolOverlayMarketRouteImport.update({
    path: '/market',
    getParentRoute: () =>
      DashboardAuthenticatedFleetShipSymbolOverlayRouteRoute,
  } as any).lazy(() =>
    import(
      './conf/_dashboard/_authenticated/fleet/$shipSymbol/_overlay.market.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_dashboard/_authenticated': {
      id: '/_dashboard/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardAuthenticatedRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/leaderboard': {
      id: '/_dashboard/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof DashboardLeaderboardRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/_authenticated/contracts': {
      id: '/_dashboard/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof DashboardAuthenticatedContractsRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteImport
    }
    '/_dashboard/_authenticated/fleet': {
      id: '/_dashboard/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof DashboardAuthenticatedFleetRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteImport
    }
    '/_dashboard/_authenticated/surveys': {
      id: '/_dashboard/_authenticated/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof DashboardAuthenticatedSurveysRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteImport
    }
    '/_dashboard/agents/$agentSymbol': {
      id: '/_dashboard/agents/$agentSymbol'
      path: '/agents/$agentSymbol'
      fullPath: '/agents/$agentSymbol'
      preLoaderRoute: typeof DashboardAgentsAgentSymbolRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/agents/': {
      id: '/_dashboard/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/systems/': {
      id: '/_dashboard/systems/'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof DashboardSystemsIndexRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/_authenticated/fleet/$shipSymbol': {
      id: '/_dashboard/_authenticated/fleet/$shipSymbol'
      path: '/$shipSymbol'
      fullPath: '/fleet/$shipSymbol'
      preLoaderRoute: typeof DashboardAuthenticatedFleetShipSymbolRouteImport
      parentRoute: typeof DashboardAuthenticatedFleetRouteImport
    }
    '/_dashboard/_authenticated/fleet/': {
      id: '/_dashboard/_authenticated/fleet/'
      path: '/'
      fullPath: '/fleet/'
      preLoaderRoute: typeof DashboardAuthenticatedFleetIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedFleetRouteImport
    }
    '/_dashboard/systems/$systemSymbol/': {
      id: '/_dashboard/systems/$systemSymbol/'
      path: '/systems/$systemSymbol'
      fullPath: '/systems/$systemSymbol'
      preLoaderRoute: typeof DashboardSystemsSystemSymbolIndexRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/_authenticated/fleet/$shipSymbol/_overlay': {
      id: '/_dashboard/_authenticated/fleet/$shipSymbol/_overlay'
      path: ''
      fullPath: '/fleet/$shipSymbol'
      preLoaderRoute: typeof DashboardAuthenticatedFleetShipSymbolOverlayRouteImport
      parentRoute: typeof DashboardAuthenticatedFleetShipSymbolRouteImport
    }
    '/_dashboard/systems/$systemSymbol/waypoint/$waypointSymbol': {
      id: '/_dashboard/systems/$systemSymbol/waypoint/$waypointSymbol'
      path: '/systems/$systemSymbol/waypoint/$waypointSymbol'
      fullPath: '/systems/$systemSymbol/waypoint/$waypointSymbol'
      preLoaderRoute: typeof DashboardSystemsSystemSymbolWaypointWaypointSymbolRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/_authenticated/fleet/$shipSymbol/_overlay/market': {
      id: '/_dashboard/_authenticated/fleet/$shipSymbol/_overlay/market'
      path: '/market'
      fullPath: '/fleet/$shipSymbol/market'
      preLoaderRoute: typeof DashboardAuthenticatedFleetShipSymbolOverlayMarketRouteImport
      parentRoute: typeof DashboardAuthenticatedFleetShipSymbolOverlayRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  AuthRouteRoute: AuthRouteRoute.addChildren({
    AuthLoginRouteRoute,
    AuthLogoutRouteRoute,
    AuthRegisterRouteRoute,
  }),
  DashboardRouteRoute: DashboardRouteRoute.addChildren({
    DashboardAuthenticatedRouteRoute:
      DashboardAuthenticatedRouteRoute.addChildren({
        DashboardAuthenticatedContractsRouteRoute,
        DashboardAuthenticatedFleetRouteRoute:
          DashboardAuthenticatedFleetRouteRoute.addChildren({
            DashboardAuthenticatedFleetShipSymbolRouteRoute:
              DashboardAuthenticatedFleetShipSymbolRouteRoute.addChildren({
                DashboardAuthenticatedFleetShipSymbolOverlayRouteRoute:
                  DashboardAuthenticatedFleetShipSymbolOverlayRouteRoute.addChildren(
                    {
                      DashboardAuthenticatedFleetShipSymbolOverlayMarketRouteRoute,
                    },
                  ),
              }),
            DashboardAuthenticatedFleetIndexRouteRoute,
          }),
        DashboardAuthenticatedSurveysRouteRoute,
      }),
    DashboardLeaderboardRouteRoute,
    DashboardAgentsAgentSymbolRouteRoute,
    DashboardAgentsIndexRouteRoute,
    DashboardSystemsIndexRouteRoute,
    DashboardSystemsSystemSymbolIndexRouteRoute,
    DashboardSystemsSystemSymbolWaypointWaypointSymbolRouteRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/_auth",
        "/_dashboard"
      ]
    },
    "/": {
      "filePath": "index.route.ts"
    },
    "/_auth": {
      "filePath": "_auth.route.ts",
      "children": [
        "/_auth/login",
        "/_auth/logout",
        "/_auth/register"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard.route.ts",
      "children": [
        "/_dashboard/_authenticated",
        "/_dashboard/leaderboard",
        "/_dashboard/agents/$agentSymbol",
        "/_dashboard/agents/",
        "/_dashboard/systems/",
        "/_dashboard/systems/$systemSymbol/",
        "/_dashboard/systems/$systemSymbol/waypoint/$waypointSymbol"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.route.ts",
      "parent": "/_auth"
    },
    "/_auth/logout": {
      "filePath": "_auth/logout.route.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.route.ts",
      "parent": "/_auth"
    },
    "/_dashboard/_authenticated": {
      "filePath": "_dashboard/_authenticated.route.ts",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/_authenticated/contracts",
        "/_dashboard/_authenticated/fleet",
        "/_dashboard/_authenticated/surveys"
      ]
    },
    "/_dashboard/leaderboard": {
      "filePath": "_dashboard/leaderboard.route.ts",
      "parent": "/_dashboard"
    },
    "/_dashboard/_authenticated/contracts": {
      "filePath": "_dashboard/_authenticated/contracts.route.ts",
      "parent": "/_dashboard/_authenticated"
    },
    "/_dashboard/_authenticated/fleet": {
      "filePath": "_dashboard/_authenticated/fleet.route.ts",
      "parent": "/_dashboard/_authenticated",
      "children": [
        "/_dashboard/_authenticated/fleet/$shipSymbol",
        "/_dashboard/_authenticated/fleet/"
      ]
    },
    "/_dashboard/_authenticated/surveys": {
      "filePath": "_dashboard/_authenticated/surveys.route.ts",
      "parent": "/_dashboard/_authenticated"
    },
    "/_dashboard/agents/$agentSymbol": {
      "filePath": "_dashboard/agents/$agentSymbol.route.ts",
      "parent": "/_dashboard"
    },
    "/_dashboard/agents/": {
      "filePath": "_dashboard/agents/index.route.ts",
      "parent": "/_dashboard"
    },
    "/_dashboard/systems/": {
      "filePath": "_dashboard/systems/index.route.ts",
      "parent": "/_dashboard"
    },
    "/_dashboard/_authenticated/fleet/$shipSymbol": {
      "filePath": "_dashboard/_authenticated/fleet/$shipSymbol.route.ts",
      "parent": "/_dashboard/_authenticated/fleet",
      "children": [
        "/_dashboard/_authenticated/fleet/$shipSymbol/_overlay"
      ]
    },
    "/_dashboard/_authenticated/fleet/": {
      "filePath": "_dashboard/_authenticated/fleet/index.route.ts",
      "parent": "/_dashboard/_authenticated/fleet"
    },
    "/_dashboard/systems/$systemSymbol/": {
      "filePath": "_dashboard/systems/$systemSymbol/index.route.ts",
      "parent": "/_dashboard"
    },
    "/_dashboard/_authenticated/fleet/$shipSymbol/_overlay": {
      "filePath": "_dashboard/_authenticated/fleet/$shipSymbol/_overlay.route.ts",
      "parent": "/_dashboard/_authenticated/fleet/$shipSymbol",
      "children": [
        "/_dashboard/_authenticated/fleet/$shipSymbol/_overlay/market"
      ]
    },
    "/_dashboard/systems/$systemSymbol/waypoint/$waypointSymbol": {
      "filePath": "_dashboard/systems/$systemSymbol/waypoint/$waypointSymbol.route.ts",
      "parent": "/_dashboard"
    },
    "/_dashboard/_authenticated/fleet/$shipSymbol/_overlay/market": {
      "filePath": "_dashboard/_authenticated/fleet/$shipSymbol/_overlay.market.route.ts",
      "parent": "/_dashboard/_authenticated/fleet/$shipSymbol/_overlay"
    }
  }
}
ROUTE_MANIFEST_END */
