export const ERROR_CODE: ReadonlyMap<string, number> = new Map([
  ['WAYPOINT_ALREADY_CHARTED', 4230],
  ['SURVEY_MUST_BE_DONE_WHILE_ORBITING', 4223],
  ['INSUFFICIENT_FUNDS', 4216],
  ['ALREADY_ACCEPTED_CONTRACT', 4501],
  ['GOOD_NOT_AVAILABLE_AT_MARKET', 4602],
])
