export const ROUTES = {
  HOME: '/',
  AUTH: '/auth',
  LOGIN: '/login',
  LOGOUT: '/logout',
  REGISTER: '/register',
  DASHBOARD: '/~',
  OVERVIEW: '/overview',
  SYSTEMS: '/systems',
  LOANS: '/loans',
  FLEET: '/fleet',
  MARKET: '/market',
  CONTRACTS: '/contracts',
  LEADERBOARD: '/leaderboard',
}
